### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by georgeedwards** [meteor/meteor-theme-hexo#23]
Hi! I am looking to convert a docs site for my existing open-source project and would love to use this as a starting point, as that is what it is set up for - and it's awesome! The project is non-competitive with meteor. Is that something you would be open to?

**Comment by lorensr** [comment]
@tmeasday I'd also be interested in using this. Who would be the person to decide whether to add an OSS license to this repo?

**Comment by SachaG** [comment]
Same here! I saw this theme being used for http://grapher.cultofcoders.com so I was wondering if it's ok to reuse it?

**Comment by jahed** [comment]
It's strange that after almost a year there's still no LICENSE defined for this project.

If your project is also open source and considering it's a public Hexo theme for Meteor (a MIT licensed project) which many are already using, I'd go ahead and use it too. If it gets revoked, you should be able to swap in one of the many other themes (if you're just using markdown for your content).

**Comment by leebenson** [comment]
Would like to know this also. Would love to use it for my [ReactQL starter kit](https://github.com/leebenson/reactql)

**Comment by leebenson** [comment]
FYI, I have a modded variant of the theme in use at https://reactql.org/docs/ too. Not only is it the best hexo theme I've seen, but I think having a common layout for these kinds of docs is a boon for users. My starter kit features Apollo heavily, so it's in keeping with the 'Meteor family' theme.

Let me know if that's not cool, and I'll make changes as necessary. But would love to keep it in use if you're okay with it.

**Comment by barbu110** [comment]
Anything on this?

**Comment by filipenevola** [comment]
Hi, the license was set to MIT on 2018 https://github.com/meteor/meteor-theme-hexo/blob/master/LICENSE 😉
